### ISSUE TITLE
InvalidArgumentException Error when trying to install

### ISSUE THREAD

**Issue by danielH0514** [jtraulle/CakeCharts#2]
when trying to install the package with composer I get this error message:

> [InvalidArgumentException]                                                   
  Could not find package jtraulle/cake-charts at any version matching your PHP version 5.6.31.0          

How can this be solved?

**Comment by jtraulle** [comment]
Minimum requirements for CakeCharts plugin is PHP >= 7.0
You need to upgrade your PHP version from 5.6 to 7.x 😉

**Comment by danielH0514** [comment]
well it ain't that easy, you should consider creating a branch for 5.x given the fact that 93% of the php websites are still running on that version.

**Comment by jtraulle** [comment]
If I find the time, I will address this, eventually.    
I am not even sure PHP >= 7.0 is really required (I've putted that because I use it in all my  projects).

Need to do some testing but I do not have the time at the moment.
