### ISSUE TITLE
Error when drawing chart

### ISSUE THREAD

**Issue by danielH0514** [jtraulle/CakeCharts#3]
I'm getting this error when I try to generate the example charts shown on the site

`Argument 6 passed to CakeCharts\Utility\Trace::__construct() must be of the type array, null given, called in /Applications/MAMP/htdocs/ots/vendor/jtraulle/cake-charts/src/View/Helper/DrawChartHelper.php on line 111`

I haven't even started to generate my own charts, I'm just testing the examples and came across this error.

Is there any way to solve it?

**Comment by jtraulle** [comment]
Thanks for reaching out,

Please, copy and paste the example code you are trying that generate this error.    
I have something in mind but need to confirm.

**Comment by danielH0514** [comment]
yes, sorry I forgot to paste it

`<?php

$series = [
  [
    ['Apples', 'Tomatoes', 'Bananas', 'Cherries'],
    [38, 22, 55, 96],
    'Ripes',
    'markers'
  ],
  [
    ['Apples', 'Tomatoes', 'Bananas', 'Cherries'],
    [11, 15, 22, 10],
    'Unripes',
    'markers'
  ]
];

echo $this->DrawChart->groupedBarChart($series);`

**Comment by jtraulle** [comment]
Thanks, that weird. That should be fixed by now ...
When did you add it as a requirement of your composer.json ?

Has been fixed in 1.1.1

**Comment by jtraulle** [comment]
Sorry, I got it.
Can you try dev-master as a requirement. Should be fixed by now. Let me know 😄

**Comment by danielH0514** [comment]
yes! It's working now!

Thanks, you are awesome!

**Comment by jtraulle** [comment]
You're welcome 🎉 
I have tagged the revision with the fix as 1.1.2 https://github.com/jtraulle/CakeCharts/releases/tag/v1.1.2 😉 

You should switch back your dependency as @stable or ^1.0 as dev-master might be unstable 😜

**Comment by danielH0514** [comment]
Done, thanks a lot!
